import React from 'react'
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./card"
import Image from 'next/image'
const AiSidebar = () => {
return (
    <div className=''>
        <div className='flex-1 flex w-full flex-col  items-center justify-center '>
            <Card className="bg-transparent w-full  border-none">
                <CardHeader className="flex flex-col mt-4 items-center">
                    <div className="w-16 h-16 rounded-full overflow-hidden mb-4">
                        <Image 
                            src="/favicon.png" 
                            alt="AI Diet"
                            width={64}
                            height={64}
                            className="w-full h-full object-cover"
                        />
                    </div>
                    <CardTitle className='text-3xl font-bold mt-1'>
                    <h1 className='text-2xl font-normal ml-5 md:ml-0 lg:text-4xl lg:font-semibold dark:from-gray-900 from-gray-300 from-0% to-75% bg-gradient-to-r  to-gray-700 dark:to-gray-400 bg-clip-text text-transparent'>PeakForm</h1>
                    </CardTitle>
                    <CardDescription>
                        <p className='text-lg mb-6'>Get a free fitness recommendation powered by AI</p>
                    </CardDescription>
                </CardHeader>
                <CardContent className={"-mt-4"}>
                    <p className="text-md">
                        Our AI-powered system analyzes your goals, preferences, and dietary restrictions
                        to create personalized meal plans and fitness recommendations. Get expert-level
                        guidance for your wellness journey.
                    </p>
                    <ul className="mt-4 space-y-2">
                        <li>• Personalized meal planning</li>
                        <li>• Custom workout routines</li>
                        <li>• Progress tracking</li>
                        <li>• Expert nutritional guidance</li>
                    </ul>
                </CardContent>
                <CardFooter className=" border-t-accent border-t   ">
                    <p className="text-xs text-muted-foreground -mt-2">
                        Note: This content is generated by AI and should be reviewed by a healthcare professional
                        before starting any new diet or exercise program.
                    </p>
                </CardFooter>
            </Card>
        </div>
    </div>
)
}

export default AiSidebar